### ISSUE TITLE
Bug in the DeviceStatusUtils.java

### ISSUE THREAD

**Issue by ivan-leschinsky** [jingle1267/android-utils#1]
There is a bug in the file: `android-utils/src/com/ihongqiqu/util/DeviceStatusUtils.java`
In the 366 line there  should be

``` java
Settings.System.VOLUME_RING
```

... to control Ring audio stream instead of media stream

**Comment by ivan-leschinsky** [comment]
@jingle1267, but there was a bug in the `setRingVolume` method in the 366 line.

**Comment by ivan-leschinsky** [comment]
Cool, thanks :smile:

**Comment by jingle1267** [comment]
You are welcome :smile:
