### ISSUE TITLE
Not able to use it with my app icon.

### ISSUE THREAD

**Issue by prithivraj** [jingle1267/android-utils#13]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/sample_app_icon) from AndroidManifest.xml:9:9-47
  is also present at [com.github.kibotu:android-utils:1.0.0] AndroidManifest.xml:23:9-45 value=(@drawable/ic_launcher).
  Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:6:5-20:19 to override.

**Comment by jingle1267** [comment]
add 'tools:replace="android:icon"' to element at AndroidManifest.xml:6:5-20:19 to override.
