### ISSUE TITLE
Failed to build gradle after adding this dependency

### ISSUE THREAD

**Issue by pravingaikwad07** [jingle1267/android-utils#15]
Added dependency:
 compile 'com.ihongqiqu.util:android-utils:1.0.0'

and repository path:
maven { url  "http://hongqiqu.bintray.com/maven" }

But getting **Error**:
Error:(139, 13) Failed to resolve: com.ihongqiqu.util:android-utils:1.0.0
Show in Project Structure dialog

**Comment by jingle1267** [comment]
Change dependencies to:
compile 'com.ihongqiqu:android-utils:1.0.2'

and repository path:
maven { url  "http://dl.bintray.com/ihongqiqu/maven" }
