### ISSUE TITLE
DataCleanManager的删除文件夹方法商榷

### ISSUE THREAD

**Issue by openproject** [jingle1267/android-utils#4]
123     private static void deleteFilesByDirectory(File directory) {
124         if (directory != null && directory.exists() && directory.isDirectory()) {
125             for (File item : directory.listFiles()) {
126                 item.delete();
127             }
128         }
129     }
为什么这个文件夹只删除一级？如果有两级怎么办？

**Comment by jingle1267** [comment]
遍历递归删除子文件和文件夹
