### ISSUE TITLE
代码让我看的很眼熟啊

### ISSUE THREAD

**Issue by kymjs** [jingle1267/android-utils#9]
[DisplayUtils.getDialogW()  ](https://github.com/jingle1267/android-utils/blob/master/app/src/main/java/com/ihongqiqu/util/DisplayUtils.java)  
这种逗比的写法除了三年前的我能想得出来，估计不会有人这么做吧。  

只是小建议，读一读 Apache 协议。[聊聊 Apache 开源协议](http://kymjs.com/manager/2015/11/21/01)  

顺便翻一下旧代码 [DensityUtils](https://github.com/kymjs/KJFrameForAndroid/blob/master/KJFrame/kjframe/src/main/java/org/kymjs/kjframe/utils/DensityUtils.java)

**Comment by jingle1267** [comment]
涛哥,多有冒犯，请见谅！

**Comment by kymjs** [comment]
没事，只是偶尔路过，看到的，那种逗比的写法还是赶紧删了吧，自己都看不下去了。
